title: <p align="center"> Naren Reddy Palupunoori </p>
logo: /assets/img/IMG-20170218-WA0023.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/naren-reddy-palupunoori-b3441a83/">LinkedIn</a> |
  <a href="https://github.com/npalupunoori">GitHub</a>
  
  <br>   
  I'm working on embedded systems at Bose Coorperation for lalst 10 years.
  I'm excited to learn new things and still see the LED glow.
  <br>
  </p>



theme: jekyll-theme-minimal
